[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
new_sale_event = "7hKa7TtHSFRFo66qW2zQ3vFTLs84AWWzsEUerqy8drJS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/franoceti/Desktop/SolanaKeys/FrasjTnXPaMpfEudjvqYAFxh5Zk74Ettqc5gtduJWXJ2.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
